# theme.toml template for a Hugo theme

name = "nascii Theme"
license = "MIT"
licenselink = "https://gitlab.com/nasciiboy/nascii-theme/LICENSE.md"
description = ""
homepage = "http://example.com/"
tags = ["prog", "nascii", "emacs", "ramen"]
features = ["no-css", "no-js", "no-analitics"]
min_version = "0.25.1"

[author]
  name = "nasciiboy"
  homepage = "nasciiboy.land"
